spring.application.name=SpringWeb

# Database Configuration

spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://gateway01.us-west-2.prod.aws.tidbcloud.com:4000/test
spring.datasource.username=4TUaTTthZLFFCEk.root
spring.datasource.password=fBR1fB8TPKnXZB5J

#JPA - Hibernate Configuration

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
